### ISSUE TITLE
点击拍照应用崩溃

### ISSUE THREAD

**Issue by ar-world** [CainKernel/CainCamera#109]
大佬，最新版本编译的应用点击拍照时崩溃。
报错如下：

    Process: com.cgfay.caincamera, PID: 24788
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.cgfay.camera.listener.OnCaptureListener.onCapture(java.nio.ByteBuffer, int, int)' on a null object reference
        at com.cgfay.camera.render.CameraRenderer.onDrawFrame(CameraRenderer.java:357)
        at com.cgfay.camera.render.CameraRenderHandler.handleMessage(CameraRenderHandler.java:73)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at com.cgfay.camera.render.CameraRenderer.run(CameraRenderer.java:481)
2020-01-08 21:47:57.315 24788-24788/com.cgfay.caincamera E/Camera-JNI: Null byte array!

**Comment by CainKernel** [comment]
前段时间为了支持CameraX重写渲染流程的时候，有部分逻辑没有恢复的。这个CameraParam单例估计后面要移除，但这边目前在忙着写编辑合成的处理功能，暂时先这么加回来吧
