### ISSUE TITLE
Setting to Latest SDK (29) App Crash

### ISSUE THREAD

**Issue by snajdovski** [CainKernel/CainCamera#111]
Setting the app to latest SDK makes the app crash.

To reproduce the problem just update the app to the latest SDK

**Comment by snajdovski** [comment]
```
2020-01-14 19:38:49.394 3881-3881/? E/Notch: hasNotchAtHuawei ClassNotFoundException
2020-01-14 19:38:49.395 3881-3881/? E/Notch: hasNotchAtVivo ClassNotFoundException
2020-01-14 19:38:49.416 3881-3966/? V/FA: Activity resumed, time: 85394268
2020-01-14 19:38:49.416 3881-3881/? E/Notch: hasNotchAtHuawei ClassNotFoundException
2020-01-14 19:38:49.417 3881-3881/? E/Notch: hasNotchAtVivo ClassNotFoundException
2020-01-14 19:38:49.429 3881-3966/? D/FA: Logging event (FE): screen_view(_vs), Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=MainActivity, ga_previous_id(_pi)=6467677531745439882, ga_screen_class(_sc)=CameraActivity, ga_screen_id(_si)=6467677531745439883}]

2020-01-14 19:38:49.433 3881-3987/? E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.social.storysnap, PID: 3881
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.social.picker.loader.AlbumDataLoader.loadInBackground(AlbumDataLoader.java:96)
        at com.social.picker.loader.AlbumDataLoader.loadInBackground(AlbumDataLoader.java:17)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```
