### ISSUE TITLE
直接报错，相机都打不开，也没法录屏

### ISSUE THREAD

**Issue by liyqxtu** [CainKernel/CainCamera#149]
E/AndroidRuntime: FATAL EXCEPTION: VideoRecorder
    Process: com.cgfay.caincamera, PID: 6947
    android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1884)
        at com.cgfay.media.recorder.VideoEncoder.<init>(VideoEncoder.java:89)
        at com.cgfay.media.recorder.VideoRecorder.onStartRecord(VideoRecorder.java:239)
        at com.cgfay.media.recorder.VideoRecorder.access$000(VideoRecorder.java:24)
        at com.cgfay.media.recorder.VideoRecorder$RecordHandler.handleMessage(VideoRecorder.java:201)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at com.cgfay.media.recorder.VideoRecorder.run(VideoRecorder.java:168)
        at java.lang.Thread.run(Thread.java:761)

**Comment by indanu** [comment]
re-download NDK side by side in sdk folder
