### ISSUE TITLE
贴纸里面除过猫耳朵贴纸，其他的一点就崩溃

### ISSUE THREAD

**Issue by woniu0936** [CainKernel/CainCamera#22]
log如下：
```
11-07 18:05:44.327 15083-15121/com.cgfay.caincamera E/OpenGLUtils: Could not compile shader 35632:
     0:8: S0032: no default precision defined for variable 'strength'
11-07 18:05:44.392 15083-15121/com.cgfay.caincamera E/OpenGLUtils: glGenTexture: glError 0x501
11-07 18:05:44.393 15083-15121/com.cgfay.caincamera E/AndroidRuntime: FATAL EXCEPTION: RenderThread
    Process: com.cgfay.caincamera, PID: 15083
    java.lang.RuntimeException: glGenTexture: glError 0x501
        at com.cgfay.filterlibrary.glfilter.utils.OpenGLUtils.checkGlError(OpenGLUtils.java:184)
        at com.cgfay.filterlibrary.glfilter.utils.OpenGLUtils.createTexture(OpenGLUtils.java:304)
        at com.cgfay.filterlibrary.glfilter.color.DynamicColorLoader.loadColorTexture(DynamicColorLoader.java:91)
        at com.cgfay.filterlibrary.glfilter.color.DynamicColorLoader.<init>(DynamicColorLoader.java:71)
        at com.cgfay.filterlibrary.glfilter.color.DynamicColorBaseFilter.<init>(DynamicColorBaseFilter.java:27)
        at com.cgfay.filterlibrary.glfilter.color.DynamicColorFilter.<init>(DynamicColorFilter.java:13)
        at com.cgfay.filterlibrary.glfilter.color.GLImageDynamicColorFilter.<init>(GLImageDynamicColorFilter.java:23)
        at com.cgfay.cameralibrary.engine.render.RenderManager.changeDynamicResource(RenderManager.java:185)
        at com.cgfay.cameralibrary.engine.render.RenderThread.changeDynamicResource(RenderThread.java:289)
        at com.cgfay.cameralibrary.engine.render.RenderHandler.handleMessage(RenderHandler.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by CainKernel** [comment]
这是fragment.glsl里面忘记加上默认精度代码导致的，有一部分手机的GPU是没带默认精度的，等下我改好提交，你将 路径下的资源删掉再重跑一边。或者你自己将assets/resource目录下的压缩包中的fragment.glsl加上以下语句：
 precision mediump float; 
然后删掉解压路径下的资源文件夹重新跑就是

**Comment by woniu0936** [comment]
好了，感谢详细讲解
