### ISSUE TITLE
第一次安装黑屏

### ISSUE THREAD

**Issue by tianshaokai** [CainKernel/CainCamera#35]
2019-01-16 17:49:34.945 24511-24511/? V/PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = ViewRoot{c761204 com.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity,ident = 15}, this = DecorView@a8ab335[GrantPermissionsActivity]
2019-01-16 17:49:34.946 24511-24511/? I/Choreographer: Skipped 5 frames!  The application may be doing too much work on its main thread.
2019-01-16 17:49:34.946 1257-26888/? D/AES: onEndOfErrorDumpThread: data_app_crash Process: com.cgfay.caincamera
    Time: 1547632174842
    Flags: 0x38e8bf46
    Package: com.cgfay.caincamera v1 (1.0)
    PID: 26842
    Foreground: Yes
    Build: OPPO/A79/A79:7.1.1/N6F26Q/1536669917:user/release-keys
    
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at com.cgfay.filterlibrary.glfilter.resource.FilterHelper.decompressResource(FilterHelper.java:84)
        at com.cgfay.filterlibrary.glfilter.resource.FilterHelper.initAssetsFilter(FilterHelper.java:66)
        at com.cgfay.caincamera.activity.MainActivity$2.run(MainActivity.java:148)
        at java.lang.Thread.run(Thread.java:761)
    
    CPU usage from 41475ms to 0ms ago (2019-01-16 17:48:53.369 to 2019-01-16 17:49:34.844):
      33% 1257/system_server: 25% user + 7.6% kernel / faults: 26665 minor 12 major
      22% 367/surfaceflinger: 12% user + 9.5% kernel / faults: 658 minor 2 major
      12% 1699/com.android.systemui: 8.8% user + 4% kernel / faults: 3505 minor 2 major
      7.9% 560/cameraserver: 6.4% user + 1.5% kernel / faults: 12637 minor
      9.8% 24511/com.android.packageinstaller: 6.9% user + 2.8% kernel / faults: 3660 minor 5 major
      5.9% 2789/com.oppo.launcher: 4.5% user + 1.3% kernel / faults: 19864 minor 7 major
      4.4% 24179/adbd: 1.1% user + 3.3% kernel / faults: 9015 minor
      4.2% 2600/com.coloros.safecenter: 3.1% user + 1% kernel / faults: 14615 minor 3 major
      4% 1664/com.nearme.statistics.rom: 3% user + 0.9% kernel / faults: 1600 minor 3 major
      2.7% 307/logd: 0.7% user + 1.9% kernel / faults: 11 minor
      2% 225/exe_cq: 0% user + 2% kernel
      1.3% 23763/com.oppo.market: 1.1% user + 0.2% kernel / faults: 2529 minor 4 major
      1.4% 366/servicemanager: 0.5% user + 0.9% kernel
      1.4% 1616/com.coloros.safecenter:clear_filter: 0.8% user + 0.6% kernel / faults: 259 minor
      1.4% 6504/com.google.android.gms: 1.1% user + 0.3% kernel / faults: 744 minor 2 major
      1.1% 25785/com.coloros.weather.service: 0.7% user + 0.3% kernel / faults: 1497 minor 14 major
      1.2% 474/disp_queue_P0: 0% user + 1.2% kernel
      1% 1555/tx_thread: 0% user + 1% kernel
      1% 227/mmcqd/0: 0% user + 1% kernel
      0.9% 18975/kworker/u17:0: 0% user + 0.9% kernel
      0.9% 2482/com.coloros.securitypermission: 0.5% user + 0.3% kernel / faults: 436 minor 1 major
      0.7% 22817/kworker/u17:2: 0% user + 0.7% kernel
      0.8% 537/aal: 0.4% user + 0.4% kernel
      0.6% 189/tee_fastcall: 0% user + 0.6% kernel
      0.8% 1747/com.android.phone: 0.6% user + 0.2% kernel / faults: 109 minor
      0.8% 16953/kworker/u16:5: 0% user + 0.8% kernel
      0.7% 24240/logcat: 0.2% user + 0.4% kernel / faults: 1 minor
      0.6% 7/rcu_preempt: 0% user + 0.6% kernel
      0.4% 24807/com.nearme.gamec
    
    --------- beginning of main
    01-16 17:49:31.501  2789  2789 D Launcher.PackageUpdateHandler: onReceive intent = Intent { act=oppo.intent.action.OPPO_START_INSTALL flg=0x10 (has extras) }
    01-16 17:49:31.501  2789  2789 D Launcher.PackageUpdateHandler: onReceive userHandle = UserHandle{0}
    01-16 17:49:31.508  1257  1257 I PackageManager: onServiceConnected
    01-16 17:49:31.508  1257  1257 I PackageManager: onServiceConnected: true, 0
    01-16 17:49:31.523  2789  2943 I OppoConvertIcon: maskBitmap -- mIconBackground == null
    01-16 17:49:31.524  2789  2789 D Launcher.Launcher: addToAllAppsListData, result = true, appInfo = App{T=null U=true UN=0 CN=ComponentInfo{com.cgfay.caincamera/downloadAppClassName} IS=4 ISrc=com.android.packageinstaller DP = 0 TP = 100 S=-1 C=-1 cell=-1/-1 span=1/1 rank=0 loc=0}
    01-16 17:49:31.524  2789  2789 D Launcher.Workspace: addApps, 11 findEmptyCell success: [1, 1] for com.cgfay.caincamera
    01-16 17:49:31.528  2789  2789 I OppoConvertIcon: maskBitmap -- mIconBackground == null
    01-16 17:49:31.545  1257  1393 I PackageManager.DexOptimizer: Running dexopt (dex2oat) on: /data/app/vmdl979895754.tmp/base.apk pkg=com.cgfay.caincamera isa=arm vmSafeMode=false debuggable=true target-filter=interpret-only oatDir = /data/app/vmdl979895754.tmp/oat sharedLibraries=null
    --------- beginning of events
    01-16 17:49:31.570  1257  1311 I am_destroy_activity: [0,118710639,6913,com.android.pack
2019-01-16 17:49:34.946 1257-26888/? W/AES: Exception Log handling...
2019-01-16 17:49:34.970 1257-26888/? D/AES: ExceptionLog: notify aed
2019-01-16 17:49:34.970 1257-26888/? D/AES:     process : com.cgfay.caincamera
2019-01-16 17:49:34.970 1257-26888/? D/AES:      module : com.cgfay.caincamera v1 (1.0)
2019-01-16 17:49:34.970 1257-26888/? D/AES:       cause : data_app_crash
2019-01-16 17:49:34.970 1257-26888/? D/AES:       pid : 26842
2019-01-16 17:49:34.970 1257-26888/? D/AEE_LIBAEE: shell: raise_exp(4, 26842, -1361051648, com.cgfay.caincamera, 0x0x7e43385f20, 0x0x0)
2019-01-16 17:49:34.971 1257-26888/? D/AEE_LIBAEE: shell: connected with AED OK
2019-01-16 17:49:34.972 596-596/? D/AEE_AED: $===AEE===AEE===AEE===$
2019-01-16 17:49:34.972 596-596/? D/AEE_AED: p 1 poll events 1 revents 1
2019-01-16 17:49:34.972 596-596/? D/AEE_AED: PPM cpu cores:8, online:8
2019-01-16 17:49:34.973 596-596/? D/AEE_AED: aed_main_fork_worker: generator 0x7e4f42fcc0, worker 0x7fe98849e0, recv_fd 12
2019-01-16 17:49:34.974 26892-26892/? D/AEE_AED: read success, handling msg (Ind, AE_IND_EXP_RAISED)
2019-01-16 17:49:34.974 26892-26892/? I/AEE_AED: [preset_info] pid: 26842, tid: -1361051648, name: UNKNOWN  >>> UNKNOWN <<<
2019-01-16 17:49:34.974 26892-26892/? V/AEE_AED: Write: Req.AE_REQ_PROCESS, seq:ffffffff
2019-01-16 17:49:34.974 1257-26888/? D/AEE_LIBAEE: shell: got the request (cmd:Req,AE_REQ_PROCESS)
2019-01-16 17:49:34.975 26892-26892/? V/AEE_AED: Read: Rsp.AE_REQ_PROCESS, seq:ffffffff, 0, 15
2019-01-16 17:49:34.975 26892-26892/? D/AEE_AED:   Process:com.cgfay.caincamera
2019-01-16 17:49:34.975 26892-26892/? V/AEE_AED: dashboard_record_update() : rec->module = com.cgfay.caincamera 
2019-01-16 17:49:34.975 26892-26892/? D/AEE_AED: Duplicated exception, cnt = 2 
2019-01-16 17:49:34.975 26892-26892/? D/AEE_AED: Last exception time: 1547632122 
2019-01-16 17:49:34.975 26892-26892/? D/AEE_AED: cur time: 1547632174 
2019-01-16 17:49:34.975 26892-26892/? D/AEE_AED: Skip for Exp level'0'
2019-01-16 17:49:34.975 1257-1343/? V/WindowManager: reevaluateVisibility focusApp:AppWindowToken{aa4ba44 token=Token{9958f57 ActivityRecord{6ed10d6 u0 com.android.packageinstaller/.permission.ui.GrantPermissionsActivity t6915}}}
2019-01-16 17:49:34.975 1257-26888/? D/AEE_LIBAEE: shell: got the request (cmd:Ind,AE_IND_LOG_CLOSE)
2019-01-16 17:49:34.975 1257-26888/? D/AEE_LIBAEE: shell: Got session close ind from AED
2019-01-16 17:49:34.976 596-596/? D/AEE_AED: clear ppm settings
2019-01-16 17:49:34.976 367-367/? I/BufferQueue: [unnamed-367-430](this:0x739d69a800,id:430,api:0,p:-1,c:-1) BufferQueue core=(367:/system/bin/surfaceflinger)
2019-01-16 17:49:34.976 596-596/? D/AEE_AED: $===AEE===AEE===AEE===$
2019-01-16 17:49:34.976 367-367/? I/BufferQueueConsumer: [unnamed-367-430](this:0x739d69a800,id:430,api:0,p:-1,c:367) connect(C): consumer=(367:/system/bin/surfaceflinger) controlledByApp=false
2019-01-16 17:49:34.977 367-367/? D/MALI: eglCreateImageKHR:501: [Crop] 0 0 0 0  img[1080 674]

**Comment by tianshaokai** [comment]
拍完照片后，点击保存 页面上没有反应，看日志才知道已经保存了

**Comment by CainKernel** [comment]
前面的ConcurrentModificationException，应该是ManActivity里面的权限处理和资源解压那里没处理好。权限问题，不影响后续的处理，你给读写文件、相机以及录音权限就好。你想改的话，验证回调那里自己处理解压资源的逻辑就好。这个不影响后续的处理。
