### ISSUE TITLE
横竖屏切换crash

### ISSUE THREAD

**Issue by AndSync** [CainKernel/CainCamera#37]
机型小米Max2 
横竖屏切换会出现崩溃现象
横竖屏切换的快的话会出现

另外横屏之后预览画面没有切换成横屏 但拍出来的视频正常
````
java.lang.RuntimeException: glCreateShader type=35633: glError 0x501
        at com.cgfay.filterlibrary.glfilter.utils.OpenGLUtils.checkGlError(OpenGLUtils.java:184)
        at com.cgfay.filterlibrary.glfilter.utils.OpenGLUtils.loadShader(OpenGLUtils.java:161)
        at com.cgfay.filterlibrary.glfilter.utils.OpenGLUtils.createProgram(OpenGLUtils.java:123)
        at com.cgfay.filterlibrary.glfilter.base.GLImageFilter.initProgramHandle(GLImageFilter.java:103)
        at com.cgfay.filterlibrary.glfilter.base.GLImageOESInputFilter.initProgramHandle(GLImageOESInputFilter.java:30)
        at com.cgfay.filterlibrary.glfilter.base.GLImageFilter.<init>(GLImageFilter.java:94)
        at com.cgfay.filterlibrary.glfilter.base.GLImageOESInputFilter.<init>(GLImageOESInputFilter.java:25)
        at com.cgfay.filterlibrary.glfilter.base.GLImageOESInputFilter.<init>(GLImageOESInputFilter.java:20)
        at com.cgfay.cameralibrary.engine.render.RenderManager.initFilters(RenderManager.java:137)
        at com.cgfay.cameralibrary.engine.render.RenderManager.init(RenderManager.java:72)
        at com.cgfay.cameralibrary.engine.render.RenderThread.surfaceCreated(RenderThread.java:147)
        at com.cgfay.cameralibrary.engine.render.RenderHandler.handleMessage(RenderHandler.java:68)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.os.HandlerThread.run(HandlerThread.java:61)
````

**Comment by CainKernel** [comment]
这个应该是一个Bug来的。没有做旋转处理。等我有时间再解决这个问题吧。最近在忙着弄播放器，抽不出时间改这个BUG。问题出现在旋转之后Surface重新创建了，改的话，估计需要从RenderThread线程入手，你可以先尝试自己解决这个问题吧。

**Comment by tianshaokai** [comment]
会不会是因为activity重新创建了

**Comment by CainKernel** [comment]
主要是渲染线程那里没处理好EGL扩展的复位问题，你可以去看GLSurfaceView里面的代码，复位是会做重新创建EGLSurface等处理的。横竖屏切换，重新创建之后，RenderThread渲染线程需要重新更新EGLSurface之类的数据。这里真正要做完整的话，渲染线程还要做一些处理才行。我现在在忙着弄短视频编辑部分的功能，等我把短视频编辑的逻辑都做完再回来改这边的Bug，望见谅。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 田绍凯 <notifications@github.com>
发送时间: Monday, February 18, 2019 2:19:33 PM
收件人: CainKernel/CainCamera
抄送: 黄文君; Comment
主题: Re: [CainKernel/CainCamera] 横竖屏切换crash (#37)


会不会是因为activity重新创建了

―
