### ISSUE TITLE
录制的片段和合成的视频有什么区别，录制了一个片段走合并流程crash

### ISSUE THREAD

**Issue by AndSync** [CainKernel/CainCamera#38]
我录制完一段想走一下合并流程crash了 请问是哪里的问题呢
````
D/CameraPreviewFragment: 开始合并
2019-01-30 11:46:58.210 3835-4851/com.abc.demo E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
2019-01-30 11:46:58.266 3835-3835/com.abc.demo V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@9cca21c
2019-01-30 11:46:58.329 3835-4851/com.abc.demo E/VideoCombiner: No video track found in /storage/emulated/0/Android/data/com.abc.demo/cache/audio/video_temp.mp4
2019-01-30 11:46:58.329 3835-4851/com.abc.demo E/VideoCombiner: No audio track found in /storage/emulated/0/Android/data/com.abc.demo/cache/audio/video_temp.mp4
2019-01-30 11:46:58.443 3835-4851/com.abc.demo I/MPEG4Writer: limits: 4294967295/0 bytes/us, bit rate: -1 bps and the estimated moov size 3195 bytes
2019-01-30 11:46:58.443 3835-4851/com.abc.demo E/MPEG4Writer: No source added
    
    --------- beginning of crash
2019-01-30 11:46:58.444 3835-4851/com.abc.demo E/AndroidRuntime: FATAL EXCEPTION: Thread-50
    Process: com.abc.demo, PID: 3835
    java.lang.IllegalStateException: Failed to start the muxer
        at android.media.MediaMuxer.nativeStart(Native Method)
        at android.media.MediaMuxer.start(MediaMuxer.java:231)
        at com.cgfay.filterlibrary.multimedia.VideoCombiner.combineVideo(VideoCombiner.java:135)
        at com.abc.demo.ui.editor.fragment.VideoRecordFragment$15.run(VideoRecordFragment.java:1382)
        at java.lang.Thread.run(Thread.java:760)
2019-01-30 11:46:58.462 3835-4851/com.abc.demo E/CrashReport: Java Crash Happen cause by Thread-50(3364)
2019-01-30 11:46:58.521 3835-4660/com.abc.demo D/MPEG4Writer: Audio track stopping
2019-01-30 11:46:58.521 3835-4687/com.abc.demo I/MPEG4Writer: Received total/0-length (385/0) buffers and encoded 385 frames. - Audio
2019-01-30 11:46:58.521 3835-4660/com.abc.demo D/MPEG4Writer: Audio track source stopping
2019-01-30 11:46:58.521 3835-4687/com.abc.demo I/MPEG4Writer: Audio track drift time: 0 us
2019-01-30 11:46:58.521 3835-4660/com.abc.demo D/MPEG4Writer: Audio track source stopped
2019-01-30 11:46:58.522 3835-4660/com.abc.demo D/MPEG4Writer: Audio track stopped
2019-01-30 11:46:58.522 3835-4660/com.abc.demo D/MPEG4Writer: Video track stopping
2019-01-30 11:46:58.522 3835-4660/com.abc.demo D/MPEG4Writer: Video track source stopping
2019-01-30 11:46:58.522 3835-4660/com.abc.demo D/MPEG4Writer: Video track source stopped
2019-01-30 11:46:58.523 3835-4688/com.abc.demo I/MPEG4Writer: Received total/0-length (263/0) buffers and encoded 263 frames. - Video
2019-01-30 11:46:58.528 3835-4660/com.abc.demo D/MPEG4Writer: Video track stopped
2019-01-30 11:46:58.528 3835-4660/com.abc.demo D/MPEG4Writer: Duration from tracks range is [8728371, 9141338] us
2019-01-30 11:46:58.528 3835-4660/com.abc.demo D/MPEG4Writer: Stopping writer thread
2019-01-30 11:46:58.539 3835-4686/com.abc.demo D/MPEG4Writer: 0 chunks are written in the last batch
2019-01-30 11:46:58.539 3835-4660/com.abc.demo D/MPEG4Writer: Writer thread stopped
2019-01-30 11:46:58.541 3835-4660/com.abc.demo I/MPEG4Writer: The mp4 file will not be streamable.
2019-01-30 11:46:58.542 3835-4660/com.abc.demo D/MPEG4Writer: Audio track stopping
2019-01-30 11:46:58.542 3835-4660/com.abc.demo D/MPEG4Writer: Video track stopping
````

**Comment by CainKernel** [comment]
看Log是找不到音频轨道和视频轨道，你检查一下录制的视频是否有问题。正常的媒体文件肯定得包含音频轨道(Audio Track) 或者 视频轨道(Video Track)的。
