### ISSUE TITLE
运行不了，可以帮忙看一下吗？

### ISSUE THREAD

**Issue by mengyaCS** [CainKernel/CainCamera#4]
CainCamera-master\ffmpeglibrary\src\main\cpp\cainmedia\cainsdl\cainsdl_egl.c
undefined reference to 'eglMakeCurrent'
undefined reference to 'eglDestroyContext'
undefined reference to 'eglDestroySurface'
undefined reference to 'eglReleaseThread'

**Comment by CainKernel** [comment]
你更新一下，我后面提交了一个更新，我最近在移植ffplay，忘记给EGL加上链接库了，你更新一下，然后用Build->Refresh Linked C++ Projects重新编译C++的文件，然后就可以了。



发自我的小米手机
在 mengyaCS <notifications@github.com>，2018年2月1日 上午10:47写道：

CainCamera-master\ffmpeglibrary\src\main\cpp\cainmedia\cainsdl\cainsdl_egl.c
undefined reference to 'eglMakeCurrent'
undefined reference to 'eglDestroyContext'
undefined reference to 'eglDestroySurface'
undefined reference to 'eglReleaseThread'

**Comment by mengyaCS** [comment]
你好，这个是我昨天下载的，刚才重新编译了一下C++，还是一样的问题。然后把那一段注释掉之后可以安转，但是在《滤镜相机》模块 报错，好像是比较器出错了。
  Process: com.cgfay.caincamera, PID: 7932
                                                                    java.util.NoSuchElementException
                                                                        at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:576)
                                                                        at java.util.Collections.max(Collections.java:1626)
                                                                        at com.cgfay.utilslibrary.CameraUtils.calculatePerfectSize(CameraUtils.java:771)
                                                                        at com.cgfay.utilslibrary.CameraUtils.setPictureSize(CameraUtils.java:434)
                                                                        at com.cgfay.utilslibrary.CameraUtils.openCamera(CameraUtils.java:91)
                                                                        at com.cgfay.utilslibrary.CameraUtils.openCamera(CameraUtils.java:60)
                                                                        at com.cgfay.cainfilter.core.RenderThread.surfaceCreated(RenderThread.java:131)
                                                                        at com.cgfay.cainfilter.core.RenderHandler.handleMessage(RenderHandler.java:85)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by CainKernel** [comment]
我后来提交了一个更新，之前由于网络问题，并没有提交到github 上，sdl 部分的话，需要加载动态库：
# 查找Android存在的库
find_library( OpenGLES-lib OpenSLES )
find_library( EGL-lib EGL )
find_library( GLESv2-lib GLESv2 )

# 链接库文件
target_link_libraries( sdl

                       ${log-lib}
                       ${OpenGLES-lib}
                       ${EGL-lib}
                       ${GLESv2-lib} )

后面你说的比较器出错问题，应该是查找相机分辨率的时候出错了，在大于期望分辨率的时候没有处理好导致的

**Comment by CainKernel** [comment]
你现在再更新一次，看看是否问题已经解决？
