### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by liosen** [CainKernel/CainCamera#88]
java.lang.IllegalArgumentException
 at android.media.MediaExtractor.selectTrack(Native Method)
 at com.cgfay.filterlibrary.multimedia.VideoCombiner.combineVideo(VideoCombiner.java:177)
 at com.cgfay.cameralibrary.engine.recorder.PreviewRecorder$4.run(PreviewRecorder.java:599)
 at java.lang.Thread.run(Thread.java:818)
录制视频的时候，部分机型会出现这个错误

**Comment by CainKernel** [comment]
这个地方后续我会更换掉。原来合成代码有些问题，并且原来的录制代码不支持倍速录制，后面我会更换成新的录制方案，详情请参考recorder的代码。

**Comment by liosen** [comment]
> 这个地方后续我会更换掉。原来合成代码有些问题，并且原来的录制代码不支持倍速录制，后面我会更换成新的录制方案，详情请参考recorder的代码。

感谢您的回复。您这个项目对我帮助很大。我在我的项目中有用到您项目的部分代码。非常感谢
