### ISSUE TITLE
打包编译arm64-v8a时，缺少libnativegdx.so包的问题

### ISSUE THREAD

**Issue by liosen** [CainKernel/CainCamera#89]
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ml.video-Ds_13ZJlZDXxYt6VvJbYcA==/base.apk"],nativeLibraryDirectories=[/data/app/com.ml.video-Ds_13ZJlZDXxYt6VvJbYcA==/lib/arm64, /data/app/com.ml.video-Ds_13ZJlZDXxYt6VvJbYcA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libnativegdx.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.badlogic.gdx.math.Matrix4.<clinit>(Matrix4.java:1555)
        at com.badlogic.gdx.math.Vector3.<clinit>(Vector3.java:25)
        at com.cgfay.cameralibrary.engine.render.RenderManager.<clinit>(RenderManager.java:435)
        at com.cgfay.cameralibrary.engine.render.RenderManager.getInstance(RenderManager.java:49)
        at com.cgfay.cameralibrary.engine.render.RenderThread.<init>(RenderThread.java:88)
        at com.cgfay.cameralibrary.engine.render.PreviewRenderer.initRenderer(PreviewRenderer.java:63)
        at com.cgfay.cameralibrary.engine.render.RenderBuilder.initRenderer(RenderBuilder.java:47)
        at com.cgfay.cameralibrary.fragment.CameraPreviewFragmentWithoutBtn.onCreate(CameraPreviewFragmentWithoutBtn.java:176)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
        at android.app.Activity.performStart(Activity.java:7118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2782)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2897)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6670)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)`
请问，这个so包，需要去哪里找，或者如何自己编译

**Comment by CainKernel** [comment]
gdxlibrary 下的abiFilters 限定了 armeabi-v7a，加上就好，各个库的编译都是独立的，记得检查清楚：https://github.com/CainKernel/CainCamera/blob/master/gdxlibrary/build.gradle

**Comment by liosen** [comment]
我加上v8a就解决了
请问是向下兼容是吗
所以APP找不到v8a包，兼容使用了v7a包。
再次感谢！
